### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by starseeker** [dmbeaglehole/instance-optimal-lsh#1]
Hi!  Does this source code have a license associated with it?

**Comment by dmbeaglehole** [comment]
No, please cite: https://arxiv.org/abs/2108.05433 if you use though!

**Comment by starseeker** [comment]
Without a license, it's not possible to use the code since it is copyright by default.  Perhaps you could consider assigning something like an MIT license?

**Comment by dmbeaglehole** [comment]
Thanks for the tip, I've added an MIT license now

**Comment by starseeker** [comment]
Awesome, thank you!
